### ISSUE TITLE
Use of STMIA

### ISSUE THREAD

**Issue by rahookds** [adamheinrich/os.h#1]
Hi Adam, 

Any reason you did not go for stmdb instead of stmaia?.

file: os_pendsv_handler.s

**Comment by adamheinrich** [comment]
Hello, `stmdb` is not part of the ARMv6-M (Cortex-M0) instruction set, see https://developer.arm.com/documentation/ddi0419/c/Application-Level-Architecture/Thumb-Instruction-Details/Alphabetical-list-of-ARMv6-M-Thumb-instructions/STM--STMIA--STMEA?lang=en.
